// frontend-part/frontend-angular/src/app/component/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  
   getYear() {
	    return new Date().getFullYear();
       }
}

<footer  class="d-flex justify-content-center" >
       <div class="copyright"  >
          <div style="margin-top : 30px;" >
				    <p>
					     <i><span>{{ getYear() }}</span> . <a  style="color: crimson;" href="mailto:farouk.bengarssallah@gmail.com">Farouk BEN GHARSSALLAH</a></i> 
					     
					</p>
					
			   </div> 
	    </div> 		   
</footer>

// frontend-part/frontend-react/src/component/Footer.js
import React, {Component} from 'react';


class Footer extends Component {
   
   
	render(){	
		  return  <footer  className="d-flex justify-content-center" >
                     <div className="copyright"  >
                        <div className="padding-nauth" >
				            <p>
					           <i><span>{ new Date().getFullYear() }</span> . <a  style={{ color: "crimson" }} href="mailto:farouk.bengarssallah@gmail.com" >Farouk BEN GHARSSALLAH</a></i> 
					     
					        </p>
					
			            </div> 
	                  </div> 		   
                   </footer>;    
				}
}

export default Footer;
